#!/bin/bash
# 卸载后清理操作
app_name1=file-cleaner
app_name2=file-permission-tool

if [ "$1" = purge ]; then
    # 完全卸载时的清理
    rm -rf /opt/apps/xiaoq_tools
    rm -rf /usr/bin/$app_name1
    rm -rf /usr/share/applications/$app_name1.desktop
    rm -rf /usr/share/icons/$app_name1.png
    rm -rf /usr/share/icons/hicolor/48x48/apps/$app_name1.png
    
    rm -rf /usr/bin/$app_name2
    rm -rf /usr/share/applications/$app_name2.desktop
    rm -rf /usr/share/icons/$app_name2.png
    rm -rf /usr/share/icons/hicolor/48x48/apps/$app_name2.png

fi

LOGUSER=$(who | awk 'NR==1{print $1}')
[ -z "$LOGUSER" ] && LOGUSER="$SUDO_USER"
HOME="/home/$LOGUSER"

# 检查主目录
if [ ! -d "$HOME" ]; then
    sudo useradd -m "$LOGUSER" >/dev/null 2>&1 || true
    sudo chmod 755 "$HOME"
fi

# 定义可能的桌面路径
DESKTOP_DIR1="$HOME/Desktop"
DESKTOP_DIR2="$HOME/桌面"

# 检查哪个桌面目录存在
if [ -d "$DESKTOP_DIR1" ]; then
    TARGET_DIR="$DESKTOP_DIR1"
elif [ -d "$DESKTOP_DIR2" ]; then
    TARGET_DIR="$DESKTOP_DIR2"
else
    TARGET_DIR="$DESKTOP_DIR1"
fi

rm -rf  "$TARGET_DIR/$app_name1.desktop"
rm -rf  "$TARGET_DIR/$app_name2.desktop"

# 更新帮助数据库
if command -v update-desktop-database >/dev/null; then
    update-desktop-database -q
fi


